download:
	wget -c 'http://code.jquery.com/jquery-1.11.2.min.js' -O jquery.min.js
	wget -c 'http://cdn.craig.is/js/mousetrap/mousetrap.min.js?9d308' -O mousetrap.min.js

clean:
	rm -f *.js

.PHONY: download clean

